// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH0_uHqxTQ8ywaPokoUayUMAJEOcX0B7s',
    appId: '1:417363167245:android:51ff6a915c220c11b62d44',
    messagingSenderId: '417363167245',
    projectId: 'najlepsze-jedzenie-123',
    storageBucket: 'najlepsze-jedzenie-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfY4bjHV1zLsoNDLvYDWi9xUeXYHJW27E',
    appId: '1:417363167245:ios:cf382b014bd0f367b62d44',
    messagingSenderId: '417363167245',
    projectId: 'najlepsze-jedzenie-123',
    storageBucket: 'najlepsze-jedzenie-123.appspot.com',
    iosClientId: '417363167245-r443nbn4otgv9ejcinplvoovmkigtkpl.apps.googleusercontent.com',
    iosBundleId: 'com.grzegorzcichon.najlepszeJedzenie',
  );
}
